---
- hosts: server
  strategy: linear
  become: true
  roles:
  - { role: openlitespeed, become: yes }
  - { role: php, become: yes }    
  - { role: mysql, become: yes }
  vars_files:
    - vars/default.yml

  tasks:
  # OpenLiteSpeed Configuration
    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: {{ owner }}
        group: {{ group }}
        mode: '0755'
      tags: [ openlitespeed ]

    - name: Set up openlitespeed ServerConf
      template:
        src: "files/httpd-config.conf.j2"
        dest: "/usr/local/lsws/conf/httpd_config.conf"
        force: yes
        owner: "lsadm"
      tags: [ openlitespeed ]

    - name: Set up openlitespeed VirtualHost
      template:
        src: "files/vhconf.conf.j2"
        dest: "/usr/local/lsws/conf/vhosts/Example/vhconf.conf"
        force: yes
        owner: "lsadm"
      tags: [ openlitespeed ]

    - name: reinstall openlitespeed
      shell: DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confdef' \
        -o Dpkg::Options::='--force-confold' -y install --reinstall openlitespeed

    - name: Install LiteSpeed repository
      shell: rm -rf /tmp/lshttpd/
      notify: Restart openlitespeed
      tags: [ openlitespeed ]

  # WordPress Configuration
    - name: Download and unpack latest WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "{{ doc_root }}"
        remote_src: yes
        creates: "{{ doc_root }}/wordpress"
      tags: [ wordpress ]

    - name: Set ownership
      file:
        path: "{{ doc_root }}"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
      tags: [ wordpress ]

    - name: Set permissions for directories
      shell: "/usr/bin/find {{ doc_root }}/wordpress/ -type d -exec chmod 750 {} \\;"
      tags: [ wordpress ]

    - name: Set permissions for files
      shell: "/usr/bin/find {{ doc_root }}/wordpress/ -type f -exec chmod 640 {} \\;"
      tags: [ wordpress ]

    - name: Set up wp-config
      template:
        src: "files/wp-config.php.j2"
        dest: "{{ doc_root }}/wordpress/wp-config.php"
      tags: [ wordpress ]

  handlers:
    - name: Restart openlitespeed
      service:
        name: lsws
        state: restarted